version: "3"

services:
    nginx:
        image: robertoadearruda/nginx
        container_name: nginx.docker
        restart: always
        volumes:
            - ".:/var/www/html"
            - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./docker/nginx/conf.d:/etc/nginx/conf.d"
            - "./docker/logs/nginx:/var/log/nginx"
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php
            - mysqldb
        links:
            - php

    php:
        image: robertoadearruda/php
        container_name: php.docker
        restart: always
        volumes:
            - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - ".:/var/www/html"
        ports:
            - "9000:9000"
        expose:
            - "9000"
        links:
            - mysqldb

    mysqldb:
        image: mysql:5.7
        container_name: mysql.docker
        restart: always
        volumes:
            - "./docker/mysql/lib:/var/lib/mysql"
            - "./docker/mysql/conf.d:/etc/mysql/conf.d"
        environment:
            - MYSQL_DATABASE=database
            - MYSQL_ROOT_PASSWORD=docker
            - MYSQL_USER=docker
            - MYSQL_PASSWORD=docker
        ports:
            - "3306:3306"

    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin.docker
        restart: always
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql.docker
        ports:
            - "8080:80"
        depends_on:
            - mysqldb